apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-instance-counter
  namespace: nginx-instance-counter
  labels:
    app: nginx-instance-counter
spec:
  selector:
    matchLabels:
      app: nginx-instance-counter
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-instance-counter
    spec:
      containers:
      - name: nginx-instance-counter
        image: fiorucci/nginx-instance-counter:4.6
        ports:
        - containerPort: 5000
        env:
          ### Optional listen address and port
          #- name: NIC_ADDRESS
          #  value: 0.0.0.0
          #- name: NIC_PORT
          #  value: 5000

          ### Optional HTTP(S) Proxy
          #- name: HTTP_PROXY
          #  value: "http(s)://username:password@proxy_ip:port"
          #- name: HTTPS_PROXY
          #  value: "http(s)://username:password@proxy_ip:port"

          ### Optional NIST NVD CVE tracking REST API key (https://nvd.nist.gov/developers/request-an-api-key)
          #- name: NIST_API_KEY
          #  value: xxxxxxxxxxxx

          ### REST API mode

          # Example for NGINX Controller

          - name: NGINX_CONTROLLER_TYPE
            value: NGINX_CONTROLLER
          - name: NGINX_CONTROLLER_FQDN
            value: "https://nginx-controller.ff.lan:443"
          - name: NGINX_CONTROLLER_USERNAME
            value: "username@domain"
          - name: NGINX_CONTROLLER_PASSWORD
            value: "thepassword"

          # Example for NGINX Instance Manager

          #- name: NGINX_CONTROLLER_TYPE
          #  value: NGINX_INSTANCE_MANAGER
          #- name: NGINX_CONTROLLER_FQDN
          #  value: "http://nim.ff.lan:11000"
          #- name: NGINX_CONTROLLER_USERNAME
          #  value: "username@domain"
          #- name: NGINX_CONTROLLER_PASSWORD
          #  value: "thepassword"

          # Example for BIG-IQ

          #- name: NGINX_CONTROLLER_TYPE
          #  value: BIG_IQ
          #- name: NGINX_CONTROLLER_FQDN
          #  value: "https://bigiq"
          #- name: NGINX_CONTROLLER_USERNAME
          #  value: "admin"
          #- name: NGINX_CONTROLLER_PASSWORD
          #  value: "admin"

          ### Push mode - push interval in seconds
          #- name: STATS_PUSH_ENABLE
          #  value: "true"
          #- name: STATS_PUSH_MODE
          #  value: CUSTOM
          #  value: NGINX_PUSH
          #- name: STATS_PUSH_URL
          #  value: "http://pushgateway.nginx.ff.lan"
          #- name: STATS_PUSH_INTERVAL
          #  value: "10"

          # Optional parameters for Basic Auth
          #- name: STATS_PUSH_USERNAME
          #  value: "authusername"
          #- name: STATS_PUSH_PASSWORD
          #  value: "authpassword"

          ### Automated e-mail reporting
            # EMAIL_ENABLED is mandatory
          #- name: EMAIL_ENABLED
          #  value: "false"
          #- name: EMAIL_INTERVAL
            # EMAIL_INTERVAL specified in days
          #  value: "5"

          #- name: EMAIL_SERVER
          #  value: "smtp.mydomain.tld"
          #- name: EMAIL_SERVER_PORT
          #  value: "25"
          #- name: EMAIL_SERVER_TYPE
            # Value can be starttls, ssl, plaintext
          #  value: "starttls"

            # Optional username/password for SMTP authentication
          #- name: EMAIL_AUTH_USER
          #  value: "username@domain.tld"
          #- name: EMAIL_AUTH_PASS
          #  value: "thepassword"

            # Reporting email sender and recipient
          #- name: EMAIL_SENDER
          #  value: "sender@domain.tld"
          #- name: EMAIL_RECIPIENT
          #  value: "recipient@domain.tld"

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-instance-counter
  namespace: nginx-instance-counter
  labels:
    app: nginx-instance-counter
spec:
  ports:
  - name: http
    port: 5000
  selector:
    app: nginx-instance-counter
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-instance-counter
  namespace: nginx-instance-counter
  annotations:
    nginx.org/proxy-connect-timeout: "30s"
    nginx.org/proxy-read-timeout: "20s"
    nginx.org/client-max-body-size: "4m"
    nginx.com/health-checks: "true"
  labels:
    app: nginx-instance-counter
spec:
  ingressClassName: nginx
  rules:
    - host: counter.nginx.ff.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-instance-counter
                port:
                  number: 5000
