FROM ubuntu:latest
RUN apt-get update

RUN apt-get install -y -q build-essential python3-pip python3-dev python3-simplejson git
RUN pip3 install --upgrade pip
RUN pip3 install --upgrade virtualenv

RUN mkdir deployment
RUN virtualenv /deployment/env/
RUN /deployment/env/bin/pip3 install flask
WORKDIR /deployment
COPY app.py .
CMD env/bin/python app.py
